apiVersion: v1
kind: Namespace
metadata:
  name: coredns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: coredns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: coredns
data:
  Corefile: |
    apps.sno.homelab.local:1053 {
      template IN A {
        answer "{{ .Name }} 60 IN A 192.168.1.176"
      }
      log
      errors
      cache 30
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: coredns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      serviceAccountName: coredns
      containers:
      - name: coredns
        image: image-registry.openshift-image-registry.svc:5000/coredns/coredns:v1.11.1
        args: ["-conf", "/etc/coredns/Corefile"]
        ports:
        - containerPort: 1053
          protocol: UDP
        - containerPort: 1053
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: config
          mountPath: /etc/coredns
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: coredns
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: coredns
spec:
  type: NodePort
  selector:
    app: coredns
  ports:
  - name: dns-udp
    port: 53
    targetPort: 1053
    protocol: UDP
    nodePort: 30053
  - name: dns-tcp
    port: 53
    targetPort: 1053
    protocol: TCP
    nodePort: 30053